### ISSUE TITLE
--header is missing

### ISSUE THREAD

**Issue by aelam** [fxm90/fastlane-plugin-swiftformat#2]
https://github.com/nicklockwood/SwiftFormat#file-headers
I just check the doc, it seems this plugin is missing `header` strip

Could you please check it

**Comment by fxm90** [comment]
I've just released version `0.3.0` that should supports the parameter. Could you please verify it is working as expected?

**Comment by aelam** [comment]
Thank you!

**Comment by aelam** [comment]
It works well thank you
